# coding: utf-8

"""
    Spotify Web API with fixes and improvements from sonallux

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 2023.8.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, confloat, conint, validator

class AudioFeaturesObject(BaseModel):
    """
    AudioFeaturesObject
    """
    acousticness: Optional[Union[confloat(le=1.0, ge=0.0, strict=True), conint(le=1, ge=0, strict=True)]] = Field(None, description="A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic. ")
    analysis_url: Optional[StrictStr] = Field(None, description="A URL to access the full audio analysis of this track. An access token is required to access this data. ")
    danceability: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable. ")
    duration_ms: Optional[StrictInt] = Field(None, description="The duration of the track in milliseconds. ")
    energy: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy. ")
    id: Optional[StrictStr] = Field(None, description="The Spotify ID for the track. ")
    instrumentalness: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="Predicts whether a track contains no vocals. \"Ooh\" and \"aah\" sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly \"vocal\". The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0. ")
    key: Optional[conint(strict=True, le=11, ge=-1)] = Field(None, description="The key the track is in. Integers map to pitches using standard [Pitch Class notation](https://en.wikipedia.org/wiki/Pitch_class). E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on. If no key was detected, the value is -1. ")
    liveness: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live. ")
    loudness: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typically range between -60 and 0 db. ")
    mode: Optional[StrictInt] = Field(None, description="Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0. ")
    speechiness: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks. ")
    tempo: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration. ")
    time_signature: Optional[conint(strict=True, le=7, ge=3)] = Field(None, description="An estimated time signature. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure). The time signature ranges from 3 to 7 indicating time signatures of \"3/4\", to \"7/4\".")
    track_href: Optional[StrictStr] = Field(None, description="A link to the Web API endpoint providing full details of the track. ")
    type: Optional[StrictStr] = Field(None, description="The object type. ")
    uri: Optional[StrictStr] = Field(None, description="The Spotify URI for the track. ")
    valence: Optional[Union[confloat(le=1, ge=0, strict=True), conint(le=1, ge=0, strict=True)]] = Field(None, description="A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry). ")
    __properties = ["acousticness", "analysis_url", "danceability", "duration_ms", "energy", "id", "instrumentalness", "key", "liveness", "loudness", "mode", "speechiness", "tempo", "time_signature", "track_href", "type", "uri", "valence"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('audio_features'):
            raise ValueError("must be one of enum values ('audio_features')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AudioFeaturesObject:
        """Create an instance of AudioFeaturesObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AudioFeaturesObject:
        """Create an instance of AudioFeaturesObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AudioFeaturesObject.parse_obj(obj)

        _obj = AudioFeaturesObject.parse_obj({
            "acousticness": obj.get("acousticness"),
            "analysis_url": obj.get("analysis_url"),
            "danceability": obj.get("danceability"),
            "duration_ms": obj.get("duration_ms"),
            "energy": obj.get("energy"),
            "id": obj.get("id"),
            "instrumentalness": obj.get("instrumentalness"),
            "key": obj.get("key"),
            "liveness": obj.get("liveness"),
            "loudness": obj.get("loudness"),
            "mode": obj.get("mode"),
            "speechiness": obj.get("speechiness"),
            "tempo": obj.get("tempo"),
            "time_signature": obj.get("time_signature"),
            "track_href": obj.get("track_href"),
            "type": obj.get("type"),
            "uri": obj.get("uri"),
            "valence": obj.get("valence")
        })
        return _obj


