# coding: utf-8

"""
    Spotify Web API with fixes and improvements from sonallux

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 2023.8.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator
from openapi_client.models.external_url_object import ExternalUrlObject
from openapi_client.models.followers_object import FollowersObject

class PlaylistUserObject(BaseModel):
    """
    PlaylistUserObject
    """
    external_urls: Optional[ExternalUrlObject] = None
    followers: Optional[FollowersObject] = None
    href: Optional[StrictStr] = Field(None, description="A link to the Web API endpoint for this user. ")
    id: Optional[StrictStr] = Field(None, description="The [Spotify user ID](/documentation/web-api/concepts/spotify-uris-ids) for this user. ")
    type: Optional[StrictStr] = Field(None, description="The object type. ")
    uri: Optional[StrictStr] = Field(None, description="The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for this user. ")
    __properties = ["external_urls", "followers", "href", "id", "type", "uri"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('user'):
            raise ValueError("must be one of enum values ('user')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlaylistUserObject:
        """Create an instance of PlaylistUserObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of external_urls
        if self.external_urls:
            _dict['external_urls'] = self.external_urls.to_dict()
        # override the default output from pydantic by calling `to_dict()` of followers
        if self.followers:
            _dict['followers'] = self.followers.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlaylistUserObject:
        """Create an instance of PlaylistUserObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlaylistUserObject.parse_obj(obj)

        _obj = PlaylistUserObject.parse_obj({
            "external_urls": ExternalUrlObject.from_dict(obj.get("external_urls")) if obj.get("external_urls") is not None else None,
            "followers": FollowersObject.from_dict(obj.get("followers")) if obj.get("followers") is not None else None,
            "href": obj.get("href"),
            "id": obj.get("id"),
            "type": obj.get("type"),
            "uri": obj.get("uri")
        })
        return _obj


