# coding: utf-8

"""
    Spotify Web API with fixes and improvements from sonallux

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 2023.8.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

class ReorderOrReplacePlaylistsTracksRequest(BaseModel):
    """
    ReorderOrReplacePlaylistsTracksRequest
    """
    uris: Optional[conlist(StrictStr)] = None
    range_start: Optional[StrictInt] = Field(None, description="The position of the first item to be reordered. ")
    insert_before: Optional[StrictInt] = Field(None, description="The position where the items should be inserted.<br/>To reorder the items to the end of the playlist, simply set _insert_before_ to the position after the last item.<br/>Examples:<br/>To reorder the first item to the last position in a playlist with 10 items, set _range_start_ to 0, and _insert_before_ to 10.<br/>To reorder the last item in a playlist with 10 items to the start of the playlist, set _range_start_ to 9, and _insert_before_ to 0. ")
    range_length: Optional[StrictInt] = Field(None, description="The amount of items to be reordered. Defaults to 1 if not set.<br/>The range of items to be reordered begins from the _range_start_ position, and includes the _range_length_ subsequent items.<br/>Example:<br/>To move the items at index 9-10 to the start of the playlist, _range_start_ is set to 9, and _range_length_ is set to 2. ")
    snapshot_id: Optional[StrictStr] = Field(None, description="The playlist's snapshot ID against which you want to make the changes. ")
    additional_properties: Dict[str, Any] = {}
    __properties = ["uris", "range_start", "insert_before", "range_length", "snapshot_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ReorderOrReplacePlaylistsTracksRequest:
        """Create an instance of ReorderOrReplacePlaylistsTracksRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ReorderOrReplacePlaylistsTracksRequest:
        """Create an instance of ReorderOrReplacePlaylistsTracksRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ReorderOrReplacePlaylistsTracksRequest.parse_obj(obj)

        _obj = ReorderOrReplacePlaylistsTracksRequest.parse_obj({
            "uris": obj.get("uris"),
            "range_start": obj.get("range_start"),
            "insert_before": obj.get("insert_before"),
            "range_length": obj.get("range_length"),
            "snapshot_id": obj.get("snapshot_id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


