# coding: utf-8

"""
    Spotify Web API with fixes and improvements from sonallux

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 2023.8.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, confloat, conint, validator

class SectionObject(BaseModel):
    """
    SectionObject
    """
    start: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The starting point (in seconds) of the section.")
    duration: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The duration (in seconds) of the section.")
    confidence: Optional[Union[confloat(le=1, ge=0, strict=True), conint(le=1, ge=0, strict=True)]] = Field(None, description="The confidence, from 0.0 to 1.0, of the reliability of the section's \"designation\".")
    loudness: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The overall loudness of the section in decibels (dB). Loudness values are useful for comparing relative loudness of sections within tracks.")
    tempo: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="The overall estimated tempo of the section in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.")
    tempo_confidence: Optional[Union[confloat(le=1, ge=0, strict=True), conint(le=1, ge=0, strict=True)]] = Field(None, description="The confidence, from 0.0 to 1.0, of the reliability of the tempo. Some tracks contain tempo changes or sounds which don't contain tempo (like pure speech) which would correspond to a low value in this field.")
    key: Optional[StrictInt] = Field(None, description="The estimated overall key of the section. The values in this field ranging from 0 to 11 mapping to pitches using standard Pitch Class notation (E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on). If no key was detected, the value is -1.")
    key_confidence: Optional[Union[confloat(le=1, ge=0, strict=True), conint(le=1, ge=0, strict=True)]] = Field(None, description="The confidence, from 0.0 to 1.0, of the reliability of the key. Songs with many key changes may correspond to low values in this field.")
    mode: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="Indicates the modality (major or minor) of a section, the type of scale from which its melodic content is derived. This field will contain a 0 for \"minor\", a 1 for \"major\", or a -1 for no result. Note that the major key (e.g. C major) could more likely be confused with the minor key at 3 semitones lower (e.g. A minor) as both keys carry the same pitches.")
    mode_confidence: Optional[Union[confloat(le=1, ge=0, strict=True), conint(le=1, ge=0, strict=True)]] = Field(None, description="The confidence, from 0.0 to 1.0, of the reliability of the `mode`.")
    time_signature: Optional[conint(strict=True, le=7, ge=3)] = Field(None, description="An estimated time signature. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure). The time signature ranges from 3 to 7 indicating time signatures of \"3/4\", to \"7/4\".")
    time_signature_confidence: Optional[Union[confloat(le=1, ge=0, strict=True), conint(le=1, ge=0, strict=True)]] = Field(None, description="The confidence, from 0.0 to 1.0, of the reliability of the `time_signature`. Sections with time signature changes may correspond to low values in this field.")
    __properties = ["start", "duration", "confidence", "loudness", "tempo", "tempo_confidence", "key", "key_confidence", "mode", "mode_confidence", "time_signature", "time_signature_confidence"]

    @validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in (-1, 0, 1):
            raise ValueError("must be one of enum values (-1, 0, 1)")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SectionObject:
        """Create an instance of SectionObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SectionObject:
        """Create an instance of SectionObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SectionObject.parse_obj(obj)

        _obj = SectionObject.parse_obj({
            "start": obj.get("start"),
            "duration": obj.get("duration"),
            "confidence": obj.get("confidence"),
            "loudness": obj.get("loudness"),
            "tempo": obj.get("tempo"),
            "tempo_confidence": obj.get("tempo_confidence"),
            "key": obj.get("key"),
            "key_confidence": obj.get("key_confidence"),
            "mode": obj.get("mode"),
            "mode_confidence": obj.get("mode_confidence"),
            "time_signature": obj.get("time_signature"),
            "time_signature_confidence": obj.get("time_signature_confidence")
        })
        return _obj


