# coding: utf-8

"""
    Spotify Web API with fixes and improvements from sonallux

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

    The version of the OpenAPI document: 2023.8.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 1.10.5, < 2",
    "aenum"
]

setup(
    name=NAME,
    version=VERSION,
    description="Spotify Web API with fixes and improvements from sonallux",
    author="sonallux",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Spotify Web API with fixes and improvements from sonallux"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    You can use Spotify&#39;s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through &lt;a href&#x3D;\&quot;https://developer.spotify.com/documentation/general/guides/authorization-guide/\&quot;&gt;OAuth 2.0&lt;/a&gt;.  The base URI for all Web API requests is &#x60;https://api.spotify.com/v1&#x60;.  Need help? See our &lt;a href&#x3D;\&quot;https://developer.spotify.com/documentation/web-api/guides/\&quot;&gt;Web API guides&lt;/a&gt; for more information, or visit the &lt;a href&#x3D;\&quot;https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\&quot;&gt;Spotify for Developers community forum&lt;/a&gt; to ask questions and connect with other developers. 
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)
